#!/bin/sh /etc/rc.common

START=99

if [ -e /tmp/needs_rgeo ]; then
  /lib/gluon/ffgt-geolocate/rgeo.sh
  /bin/rm -f /tmp/needs_rgeo
fi

newcommunity="`/sbin/uci get gluon-node-info.@location[0].siteselect 2>/dev/null`"
curcommunity=`/usr/bin/lua -e "local site=require 'gluon.site_config' local curcommunity=site.site_selectcode or 'none' print (curcommunity)"`
locode="`/sbin/uci get gluon-node-info.@location[0].locode 2>/dev/null`"

if [ "X${locode}" != "X" -a "X${newcommunity}" != "X" -a "X${curcommunity}" != "X" ]; then
  # All set ... Consistency check.
  if [ "${newcommunity}" == "${curcommunity}" -a "${newcommunity}" == "${locode}" ]; then
    # newcommunity == currcommunity == locode, excellent! Stop the cron job ...
    /bin/sed -i -e 's%^.*$%#&%g' /lib/gluon/cron/site-select
  fi
fi

if [ "X${locode}" == "X" ]; then
  # Missing. Try to fix via rgeo call on next run via cron
  touch /tmp/needs_rgeo
elif [ "${newcommunity}" != "${locode}" ]; then
  # Mismatch. Locode prevails, thus we need to reconfigure.
  newcommunity="${locode}"
fi

if [ "X${newcommunity}" == "X" ]; then
  # siteselect isn't there, shouldn't happen. Check for locode.
  if [ "X${locode}" != "X" ]; then
     newcommunity="${locode}"
  fi
fi

if [ "X${newcommunity}" != "X" -a "${newcommunity}" != "${curcommunity}" ]; then
  srcfile="`/sbin/uci get siteselect.${newcommunity}.path`"
  /bin/cp ${srcfile} /lib/gluon/site.conf
  /sbin/uci set gluon-node-info.@location[0].siteselect="${newcommunity}"
  /sbin/uci commit
  /lib/gluon/site-upgrade
  rebootloopprevention="`/sbin/uci get gluon-node-info.@location[0].rebootloopprevention 2>/dev/null`"
  if [ "X${rebootloopprevention}" == "X" ]; then
    /sbin/uci set gluon-node-info.@location[0].rebootloopprevention='1'
    /sbin/uci commit
    # Reboot into new config in 60 seconds ...
    ((sleep 60 ; reboot)&) #))
  fi
fi
